/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package guis;

import entidades.QuimicoConstituyente;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import residuos_negocios.CtrlQuimicos;
import residuos_negocios.CtrlResiduos;


/**
 *
 * @author Equipo 2 - Residuos peligrosos
 */
public class FrmRegistrarResiduo extends javax.swing.JFrame {

    private final CtrlQuimicos ctrlQuimicos;
    
    /**
     * Creates new form FrmRegistrarResiduo
     */
    public FrmRegistrarResiduo() {
        initComponents();
        this.ctrlQuimicos = new CtrlQuimicos();
        this.llenarTabla();
    }
    
    
    
    
    private String getNombreQuimicoSeleccionado(){
        int indiceFilaSeleccionada = this.tblQuimicos.getSelectedRow();
        if(indiceFilaSeleccionada != -1){
            DefaultTableModel modelo = (DefaultTableModel)this.tblQuimicos.getModel();
            int indiceColumnaNombre = 0;
            String NombreQuimicoSeleccionado = (String) modelo.getValueAt(indiceFilaSeleccionada, 
                indiceColumnaNombre);
            return NombreQuimicoSeleccionado;
        }else{
            return null;
        }
    }
    
    private String getNombreComponenteSeleccionado(){
        int indiceFilaSeleccionada = this.tblComponentes.getSelectedRow();
        if(indiceFilaSeleccionada != -1){
            DefaultTableModel modelo = (DefaultTableModel)this.tblComponentes.getModel();
            int indiceColumnaNombre = 0;
            String NombreQuimicoSeleccionado = (String) modelo.getValueAt(indiceFilaSeleccionada, 
                indiceColumnaNombre);
            return NombreQuimicoSeleccionado;
        }else{
            return null;
        }
    }
    
    private int getIndiceComponenteSeleccionado(){
        int indiceFilaSeleccionada = this.tblComponentes.getSelectedRow();
        if(indiceFilaSeleccionada != -1){
            return indiceFilaSeleccionada;
        }else{
            return -1;
        }
    }
    
    private int getIndiceQuimicoSeleccionado(){
        int indiceFilaSeleccionada = this.tblQuimicos.getSelectedRow();
        if(indiceFilaSeleccionada != -1){
            return indiceFilaSeleccionada;
        }else{
            return -1;
        }
    }
    
    private void agregarTablaComponentes()
    {
        DefaultTableModel modeloTablaComponentes = (DefaultTableModel)this.tblComponentes.getModel();
        DefaultTableModel modeloTablaQuimicos = (DefaultTableModel)this.tblQuimicos.getModel();
        String nombreQuimicoSeleccionado = getNombreQuimicoSeleccionado();
        int idQuimicoSeleccionado = getIndiceQuimicoSeleccionado();
        modeloTablaComponentes = ctrlQuimicos.agregarTablaComponentes(modeloTablaComponentes, nombreQuimicoSeleccionado);
        modeloTablaQuimicos = ctrlQuimicos.removerTablaQuimicos(modeloTablaQuimicos, idQuimicoSeleccionado);
//        this.tblComponentes.setModel(modeloTabla);
    }
    
    private void removerTablaComponentes()
    {
        DefaultTableModel modeloTablaComponentes = (DefaultTableModel)this.tblComponentes.getModel();
        DefaultTableModel modeloTablaQuimicos = (DefaultTableModel)this.tblQuimicos.getModel();
        String nombreComponenteSeleccionado = getNombreComponenteSeleccionado();
        int indiceComponenteSeleccionado = getIndiceComponenteSeleccionado();
        modeloTablaComponentes = ctrlQuimicos.removerTablaComponentes(modeloTablaComponentes, indiceComponenteSeleccionado);
        modeloTablaQuimicos = ctrlQuimicos.agregarTablaQuimicos(modeloTablaQuimicos, nombreComponenteSeleccionado);
    }
    
    private void llenarTabla(){
        DefaultTableModel modeloTabla = (DefaultTableModel)this.tblQuimicos.getModel();
        modeloTabla = ctrlQuimicos.llenarTablaQuimicos(modeloTabla);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblQuimicos = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblComponentes = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registrar residuo");

        tblQuimicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Químicos disponibles"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblQuimicos);
        if (tblQuimicos.getColumnModel().getColumnCount() > 0) {
            tblQuimicos.getColumnModel().getColumn(0).setResizable(false);
        }

        tblComponentes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Componentes del nuevo residuo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblComponentes);
        if (tblComponentes.getColumnModel().getColumnCount() > 0) {
            tblComponentes.getColumnModel().getColumn(0).setResizable(false);
        }

        jLabel3.setText("Código");
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoKeyTyped(evt);
            }
        });

        jLabel4.setText("Nombre");
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnRemover.setText("Remover");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnRemover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(5, 5, 5)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(9, 9, 9)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btnGuardar)
                        .addGap(47, 47, 47)
                        .addComponent(btnCancelar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(btnAgregar)
                                .addGap(18, 18, 18)
                                .addComponent(btnRemover))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGuardar)
                            .addComponent(btnCancelar)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!Character.isDigit(c))
        {
            evt.consume();
        }
        if(txtCodigo.getText().length() >= 6)
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtCodigoKeyTyped

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        CtrlResiduos ctrlResiduos = new CtrlResiduos();
        DefaultTableModel modeloTablaComponentes = (DefaultTableModel)this.tblComponentes.getModel();
        String nombre = txtNombre.getText();
        String codigo = txtCodigo.getText();
        if(ctrlResiduos.verificarFormato(nombre, modeloTablaComponentes))
        {
            if(ctrlResiduos.verificarDuplicados(codigo, nombre, modeloTablaComponentes))
            {
                if(ctrlResiduos.agregar(codigo, nombre, modeloTablaComponentes))
                {
                    JOptionPane.showMessageDialog(this, "Se agrego correctamente el Residuo", 
                    "Información", JOptionPane.INFORMATION_MESSAGE);
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "No se pudo agregar el Residuo", 
                    "ERROR", JOptionPane.ERROR_MESSAGE);
                }
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Este Residuo ya existe", 
                "Advertencia", JOptionPane.WARNING_MESSAGE);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Los datos del Residuo tienen el formato incorrecto o la lista de componentes químicos esta vacía", 
                "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        if(getNombreQuimicoSeleccionado()!= null)
        {
            agregarTablaComponentes();
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Debes seleccionar un químico", 
                "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        // TODO add your handling code here:
        if(getIndiceComponenteSeleccionado() != -1)
        {
            removerTablaComponentes();
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Debes seleccionar un componente", 
                "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        new FrmPrincipal().setVisible(true);
        super.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarResiduo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarResiduo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarResiduo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarResiduo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmRegistrarResiduo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnRemover;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblComponentes;
    private javax.swing.JTable tblQuimicos;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
